version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.19
    ports:
      - '3306:3306'
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty123
      - MYSQL_DATABASE=mysql
